### ISSUE TITLE
PHP error in index.php

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/obento#259] opened 2014-10-31 18:58 UTC
The Drupal log is showing errors when unknown variables appear in the url for /search-all:

https://library.gwu.edu/search-all?this=that 
generates these 2 errors:
Notice: Undefined index: query in include() (line 45 of /var/www/obento/index.php).
Notice: Undefined index: query in include() (line 17 of /var/www/obento/index.php).

The "legitimate" use-case is when people choose to override the responsive site using the "desktop" link, which passes mobile=no (or conversely mobile=yes)
https://library.gwu.edu/search-all?mobile=no

**Comment by StudioZut** [comment] 2015-02-09 16:35
The current error in the Drupal php log when no query is defined is:

Notice: Undefined index: query in include() (line 83 of /var/www/obento/index.php). 

I see what you mean, it is only generated when the query parameter is not passed along. Since we now have an actual page at /search-all, can we add some behavior to a !isset($_GET["query"]) check?

**Comment by kerchner** [comment] 2016-07-26 17:23
Duplicate of #370, which was resolved in #371.  Closing.

**Closed by kerchner** 2016-07-26 17:23 UTC
Labels: bug, duplicate
